### ISSUE TITLE
Custom Mapping Futures

### ISSUE THREAD

**Issue by Tritonfc** [netglade/auto_mappr#150]
I am trying to add a custom map value gotten from a future as such:
```
@AutoMappr([
  MapType<UserClass, LearningClass>(
    fields: [
      Field('id', from: 'id'),
      Field('name', whenNull: 'JS1'),
      Field('isAvailable', custom: Mappr.mapIsAvailable),
     
    ],
  ),
])

class Mappr extends _$Mappr{

static Future<bool> mapIsAvailable(UserClass userClass)  async{
 SecureStorageController secureStorageController = SecureStorageController();
 final grade =  await secureStorageController.getUserClass();

  return userClass.name == grade;

 
}
```
However i dont want to assign the future directly to the isAvailable. Just the pure value. Are there any provisions for that without having to explicitly use "then" in the Field block.

**Comment by tenhobi** [comment]
I would argue that this use case should not be done using auto_mappr, which is about object mapping mostly to make objects from different layers independent. This adds a logit that should not be part of mapping itself.

**Comment by Tritonfc** [comment]
I eventually went this route:
```
extension ConvertToLearningClass on UserClass {
  LearningClass convertToClass(String chosenClass) {
    return LearningClass(
        id: id, name: name ?? "JS1", isAvailable: name == chosenClass);
  }
}
```
The `chosenClass` had to be fetched as future, which led to that attempt. But I do see how much better it is to separate out such logic from mapping to reduce unnecessary complexity
