### ISSUE TITLE
Possibility to ignore elements in a list when mapping goes wrong for one element

### ISSUE THREAD

**Issue by Windisch94** [netglade/auto_mappr#206]
I'd like to convert lets say a list
`final listA = [correctObject, mappingGoesWrongObject, correctObject]`
into a list
`final listB = [correctMappedObject, correctMappedObject]`

where i can ignore all elements where the mapping goes wrong.
I hope you can get the idea - i haven't seen the possibility to do this in the current implementation.

**Comment by tenhobi** [comment]
Hi @Windisch94, good idea, we might do it somehow as part of already proposed updates in #204.

**Comment by petrnymsa** [comment]
Hi @Windisch94 new version just landed with safeMapping. You should be able to filter-out failed mappings.

Closing now, feel free to repoen if you think that safeMapping doesn't cover your needs.
