### ISSUE TITLE
Missing concrete implementation of 'AutoMapprInterface.useSafeMapping'.

### ISSUE THREAD

**Issue by braswelljr** [netglade/auto_mappr#217]
**Describe the bug**
Missing concrete implementation of 'AutoMapprInterface.useSafeMapping'.

**To Reproduce**
Code to reproduce issue: 
- Upgrade `auto_mappr_annotation` to version `2.2.0`.
- Run `flutter pub run build_runner build --delete-conflicting-outputs -d`.
- Error will show on `auto_mappr_annotation` implementations.

**Expected behavior**
Missing concrete implementation of `AutoMapprInterface.useSafeMapping` on implementations.

**Version info**
 - Package version : 2.2.0

**Additional context**

**Comment by petrnymsa** [comment]
Hi @braswelljr , which version of auto_mappr you are using? You need auto_mappr 2.5.0

**Comment by braswelljr** [comment]
@petrnymsa  using auto_mappr 2.5.0 does not work.

**Comment by petrnymsa** [comment]
Can you share pubspec.lock and reproducible example?

**Comment by petrnymsa** [comment]
I am closing this issue for now. If the issue persists, feel free re-open.
