### ISSUE TITLE
Improved constructor selection strategy

### ISSUE THREAD

**Issue by tenhobi** [netglade/auto_mappr#4]
We are currently using the "use the one with the most parameters" strategy to find the best constructor. Or one can also set the constructor in the annotation.

With this enhancement, the strategy should find a better-fitter constructor according to field names, types etc.

**Comment by wstrange** [comment]
Perhaps related (happy to file a separate issue - LMK)

I have a grpc generated class with a private and a default constructor:

```dart
EventM._() : super();

  factory EventM({
    $core.int? id,
... stuff omitted
}
```

Instead of using the default constructor, auto_mappr wants to use the private  `EventM._()` constructor.

Not a show stopper, as I can do this to get around it:

`  MapType<EventI,EventM>(constructor: ''),`

**Comment by tenhobi** [comment]
Hi @wstrange 🙌. Ah! We should filter out private constructors; good catch!

If you wish, you can make a PR (otherwise, I will do the PR on Sunday or Monday). The code to change is here https://github.com/netglade/auto_mappr/blob/main/packages/auto_mappr/lib/src/builder/map_model_body_method_builder.dart#L315 where adding something like `!c.isPrivate` might work.

---

Right now, I am not really sure why we filter out factory constructors, cc @petrnymsa? If anything, we may sort them below so they are not prioritised, but should we also choose them if they are only constructors?

**Comment by petrnymsa** [comment]
@tenhobi Factory constructors are ommitted beacuase of JsonSerializable, where you have factory constructor like

`ClassX.fromJson(Map<String, dynamic>)`

Issue is, if the target class has different constructor with one parameter, we can not guarantee that other constructor than `fromJson` constructor is selected. 

---

I think that we should
1. Allow any public constructor (factory, non-factory)
2. By default ignore fromJson constructor (if exists)
3. Allow to override rule 2. by implicitly setting ` MapType<A,B>(constructor: 'fromJson')`
