### ISSUE TITLE
Support import aliases

### ISSUE THREAD

**Issue by DevNico** [netglade/auto_mappr#55]
I sometimes have identically named models in an api and domain package. Therefore I need to alias the import of the api package. This unfortunately generates the model names without the import alias resulting in invalid mapping code.

```dart
import 'package:api/api.dart' as api;
import 'package:auto_mappr_annotation/auto_mappr_annotation.dart';
import 'package:domain/domain.dart';

part 'test_mapper.g.dart';

@AutoMappr([
  MapType<Test, api.Test>(),
  MapType<api.Test, Test>(),
])
class Mappr extends $Mappr {}
```

**Comment by DevNico** [comment]
I'll take a look at this :)

**Comment by tenhobi** [comment]
@DevNico hey, I already have WIP implementation for this. :)

**Comment by DevNico** [comment]
Oh alright guess I'll just wait for you then :D
