### ISSUE TITLE
Enum fallback value

### ISSUE THREAD

**Issue by DevNico** [netglade/auto_mappr#56]
I'd like to define a fallback enum value for "unknown" values.

**Comment by tenhobi** [comment]
Hi @DevNico, that's a good catch!

Right now, we require that the target is a superset of the source. And from the implementation (https://github.com/netglade/auto_mappr/blob/main/packages/auto_mappr/lib/src/builder/enum_assignment_builder.dart#L15), we probably forgot that if null is passed, we should return the `whenSourceIsNull` if present, that should also be added.

To comply with the mentioned requirement, we can relax it when the `whenSourceIsNull` argument is set and don't enforce it, and if that happens, return that value instead, aka your 'fallback enum value'. 👍 

With something like this: 

```dart
values.firstWhere((x) => x.name == model.name, orElse: () => whenSourceIsNull)
```

Let us know if you want to take this issue and implement the changes. We can also discuss it on our Discord. 🙌

**Comment by DevNico** [comment]
I'll take a look at this, you can assign me to this issue.
