### ISSUE TITLE
Implement Dart 3 recods

### ISSUE THREAD

**Issue by tenhobi** [netglade/auto_mappr#58]
Implement support for record types.

Note: we might merge it even before we have Dart 3 since the analyzer already can know the record type.

**Comment by Abdulrasheed1729** [comment]
To implement for the Dart 3 records, in my opinion, I think it would be better to first convert it to a map first for it to work, for example like a `toMap()` extension function, but it seems difficult to implement. And it is almost impossible according to what is [here.](https://github.com/dart-lang/language/issues/2886)
Or is there something I'm missing?

**Comment by tenhobi** [comment]
I haven't looked much into it, but I initially thought we could get positional and named things out of it, similar to the constructor, and do something about it?

**Comment by Abdulrasheed1729** [comment]
Oh, yes, thanks, I just found out there is `RecordType` :smile: in the `anlayzer` library with the `namedFields` and `positionalFields` getters, I will try to get something out of that :+1:

**Comment by Abdulrasheed1729** [comment]
I've been trying to mess around with some things, what if we have the type `Record` use as a primitive type 🤔? Like what is in this extension.
```dart
extension DartTypeExtension on DartType {
  bool get isPrimitiveType =>
      isDartCoreNum ||
      isDartCoreInt ||
      isDartCoreDouble ||
      isDartCoreString ||
      isDartCoreBool ||
      isDartCoreEnum ||
      isDartCoreSymbol ||
      isDartCoreRecord;
}
```
And have something like this
```dart
@AutoMappr([
  MapType<RecordHolderDto, RecordHolder>(),
])
class Mappr extends $Mappr {}

class RecordHolder {
  final Record value;

  RecordHolder(this.value);
}

class RecordHolderDto {
  final Record value;

  RecordHolderDto(this.value);
}
```

I still doubt if this is right, but I just want you to see, before I create a PR.

**Comment by tenhobi** [comment]
I think the difference between primitives and iterable/map right now is that we pass a primitive just like that, and we map each part of iterable/map.

Meaning in the Iterable I can have `List<UserDto> -> List<User>`, in Map, I can have `Map<KeyDto, ValueDto> -> Map<Key, Value>`, and in Record, I can have `(UserDto, AddressDto, school: SchoolDto, ...) -> (User, Address, school: School, ...)`.

I am not sure how the records mapping should work exactly either because we didn't use it yet. :D That is what this issue is about -- do research and probably do it similarly to list/map mappings. It's for sure a tricky issue to do.

**Comment by Abdulrasheed1729** [comment]
Yes, it is quite tricky one to implement. I will make more findings and try to imitate that of map/list.
Thanks for the feedback.

**Comment by tenhobi** [comment]
Will be available in v2
