### ISSUE TITLE
Implicit mappings of nested objects

### ISSUE THREAD

**Issue by tenhobi** [netglade/auto_mappr#6]
If an object has nested objects, right now all nested objects have to be added to the `@AutoMappr` annotation. With this feature, the unknown mappings should try to generate code for them implicitly, so users can eventually only mark the topmost object mapping.

Aka for this object structure

- alpha
  - beta
    - gama
    
it will be possible to only map `AlphaDto to Alpha` without specifying `BetaDto to Beta` and `GamaDto to Gama`.

**Comment by petrnymsa** [comment]
Closing for now as it leads to "too much black magic behind the scenes".
