### ISSUE TITLE
Allow using `from` and `custom` together

### ISSUE THREAD

**Issue by DevNico** [netglade/auto_mappr#61]
I just found the use case that I have two Models like the following (shortened):

```dart
class Dto {
  final String dateTimeValue;
}

class Domain {
  final DateTime dateTime;
}


@AutoMappr([
  MapType<Domain, Dto>(fields: [
    Field(
      'dateTimeValue',
      from: 'dateTime',
      custom: Mappr._dateTimeToIso8601String,
    ),
  ]),
])
class Mappr extends $Mappr {
  static String _dateTimeToIso8601String(DateTime dateTime) {
    return dateTime.toIso8601String();
  }
}

```

I therefore need to convert the DateTime to a String using a custom function but also define the `from` Parameter.

I don't want to write the custom mapping function over and over again so to increase reusability I'd like the `from` parameter to narrow the input for the custom mapping function.

**Comment by DevNico** [comment]
Basically I'd like the above code to produce a working mapper. By defining `from` and `custom` I'd expect the input the custom function gets to not be the entire source model but just the selected field using the `from` parameter.

**Comment by DevNico** [comment]
Maybe the custom function could be made smarter in general. Currently it always gets the entire source model. If the custom function defines the type of the inferred source field it should get that passed in its parameter.

E.g. the following should also work in that case:
```dart
class Dto {
  final String dateTime;
}
class Domain {
  final DateTime dateTime;
}


@AutoMappr([
  MapType<Domain, Dto>(fields: [
    Field(
      'dateTimeValue',
      custom: Mappr._dateTimeToIso8601String,
    ),
  ]),
])
class Mappr extends $Mappr {
  static String _dateTimeToIso8601String(DateTime dateTime) {
    return dateTime.toIso8601String();
  }
}
```

**Comment by tenhobi** [comment]
While I get your point, I think it will be very confusing if the `custom` works differently depending on what other parameters are used. So right now, I think having a custom function that takes the whole source object as a parameter is the best way to "combine `from` and `custom`."

I think when we do something about #60 and #11 it will be good enough solution for these usages?

**Comment by DevNico** [comment]
I thought about this some more and #60 would cover my use case if I can specify a `TypeConverter` for a specific `MapType`.

Let's look at a different example where a specific mapping function (e.g. map just a single field) would be valuable.

```dart
class UserId {
  const UserId(this.value);
  final int value;
}

class AccountId {
  const AccountId(this.value);
  final int value;
}

class User {
  final UserId userId;
  final AccountId accountId;
}

class UserDto {
  final int userId;
  final int accountId;
}

@AutoMappr([
  MapType<UserDto, User>(fields: [
    Field('userId', customField: UserId.new),
    Field('accountId', customField: AccountId.new),
  ]),
])
class Mappr extends $Mappr {}
```

My initial idea of having the custom function infer the types e.g. source type is `UserId` and the given Function to custom accepts a `UserId` as its parameter and therefore gets passed just the field might be confusing. Therefore I imagined a new parameter for just mapping the field.

You could certainly also make this work with a `TypeConverter` API this could look something like this:

```dart
@AutoMappr([
  MapType<UserDto, User>(fields: [
    Field('userId', type: TypeConverter(UserId.new)),
    Field('accountId', type: TypeConverter(AccountId.new)),
  ]),
])
class Mappr extends $Mappr {}
```

Even though in that case the "Type" Converter literally just acts as a single field converter function.

**Comment by tenhobi** [comment]
I think we can make those type converters on fields, on maptype (for all fields), and even on automappr (for everything inside the current auto mapper "module"). So I would close this issue in favor or #60 and think of a way in that issue to make it happen?

Because the idea of custom vs typeConverter is a bit different.

**Comment by DevNico** [comment]
Yup makes sense. I think all my use cases are covered by type converters even though I still see the possibility of this becoming relevant. I'll reopen this if ever necessary.
