### ISSUE TITLE
Can Convert Model inside another model or not?

### ISSUE THREAD

**Issue by the-best-is-best** [netglade/auto_mappr#76]
class a{
final String x;
final B b;
a(this.x, this.b);
}

class B{
final String y;
B(this.y);
}

**Comment by petrnymsa** [comment]
@the-best-is-best  Hi, can you clarify more what are you trying to achieve? 

Nested classes inside models are supported. For example suppose we have 

```dart
class UserDto {
   AddressDto address;
  ...
}

class AddressDto { }

// and destination models 

class User {
  Address address;
}

class Address {} 
```

You can configure AutoMappr to have defined mapping between UserDto -> User and AddressDto -> Address

```dart
@AutoMappr([
   MapType<UserDto, User>(),
   MapType<AddressDto, Address>(),
])
class OurMappr extends $OurMappr {}
```

**Comment by the-best-is-best** [comment]
thanks it working

**Comment by the-best-is-best** [comment]
thanks for this library
