### ISSUE TITLE
Bad state: No element 

### ISSUE THREAD

**Issue by jacktattersall1** [netglade/auto_mappr#77]
**RESOLVED**
the below issue arose when trying to convert from UInt8list to List<int> without a custom field mapping.

**Describe the bug**
Apologies for the lack of a clear description.
I have been using mappr succesfully for about 50 conversions with varying complexity.
I then created another 30+ mappings with custom fields, and now out of the blue, whenever i run the tool i get

```
[SEVERE] auto_mappr on lib/clients/transport_models/mappr.dart (cached):

Bad state: No element
[SEVERE] Failed after 101ms
```

**To Reproduce**
dart run build_runner build

**Expected behavior**
generation to complete

**Version info**
`auto_mappr: ^1.3.1`

**Additional context**
```
[SEVERE] auto_mappr on lib/clients/transport_models/mappr.dart:

Bad state: No element
dart:core                                                                 _Array.first
package:auto_mappr/src/builder/value_assignment_builder.dart 77:80        ValueAssignmentBuilder._assignIterableValue
package:auto_mappr/src/builder/value_assignment_builder.dart 44:14        ValueAssignmentBuilder.build
package:auto_mappr/src/builder/map_model_body_method_builder.dart 255:13  MapModelBodyMethodBuilder._mapConstructor
package:auto_mappr/src/builder/map_model_body_method_builder.dart 227:12  MapModelBodyMethodBuilder._processConstructorMapping
package:auto_mappr/src/builder/map_model_body_method_builder.dart 58:35   MapModelBodyMethodBuilder.build
package:auto_mappr/src/builder/auto_mappr_builder.dart 94:15              AutoMapprBuilder._buildMethods.<fn>
package:code_builder/src/specs/method.g.dart 333:33                       _$MethodBuilder.update
package:code_builder/src/specs/method.g.dart 38:29                        new _$Method
package:auto_mappr/src/builder/auto_mappr_builder.dart 79:9               AutoMapprBuilder._buildMethods
package:auto_mappr/src/builder/auto_mappr_builder.dart 40:34              AutoMapprBuilder.build.<fn>.<fn>
package:code_builder/src/specs/class.g.dart 292:33                        _$ClassBuilder.update
package:code_builder/src/specs/class.g.dart 34:28                         new _$Class
package:auto_mappr/src/builder/auto_mappr_builder.dart 37:13              AutoMapprBuilder.build.<fn>
package:code_builder/src/specs/library.g.dart 186:33                      _$LibraryBuilder.update
package:code_builder/src/specs/library.g.dart 24:30                       new _$Library
package:auto_mappr/src/builder/auto_mappr_builder.dart 32:12              AutoMapprBuilder.build
package:auto_mappr/src/generator/auto_mappr_generator.dart 89:28          AutoMapprGenerator.generateForAnnotatedElement
package:source_gen/src/generator_for_annotation.dart 53:30                GeneratorForAnnotation.generate
package:source_gen/src/builder.dart 355:33                                _generate
```

Nothing more to add, is there anyway to get any more information on this issue.
I am happy to post my _Mappr class but it is quite large.

**Comment by petrnymsa** [comment]
Hi @jacktattersall1 , thank you for report. 

I can easily reproduce mentioned issue with sample mapping 

```dart
class Source {
  final Uint8List data;
  Source({
    required this.data,
  });
}

class Destination {
  final List<int> data;

  Destination({
    required this.data,
  });
}

@AutoMappr([
  MapType<Source, Destination>(),
])
class Mappr extends $Mappr {}
```

I will fix it as soon as possible.

**Comment by petrnymsa** [comment]
I've analyzed issue and we probably can come up with following solution: 

Build-in  specialized variants of `List<int>` -  `Uint8List`, `Uint16List`, `Uint32List`,`Uint64List` can be automatically supported with following rules

- When they are in source -> can be automatically mapped to List<int>
- When they are mapped from List<int> into specialized type - mappr will generate `Uint8List.fromList(source)` mapping (or its variant)

Any different mapping will not be supported, especially any "cross" variant mapping, e.g from Uint8List -> Uint64List. These special List<int> variants are meant for critical optimizations and it still should be responsibility of developer to come up with proper conversion.
