### ISSUE TITLE
Add support for mappr's module dependencies

### ISSUE THREAD

**Issue by petrnymsa** [netglade/auto_mappr#79]
Suppose we have shared Dto which describes common data like

```dart
class CommonDto {
  final String id;
  final String name;
  ...
}
```

This Dto can be used acrros different dtos.  For each mappr's module where we define concrete mappings for Dtos from such module. 
Expectation is that mapping "CommonDto -> CommonObject" which is defined in main mapper should be available. 

There should be way to concrete "AutoMappr" either mark as "Only as module" type thus some mappr's checks will be removed OR somehow tell AutoMappr that there is "globally" available mapping. 

Concrete example:

Mapping between **CommonDto** -> **CommonObject** should be defined "globally" 

```dart
@AutoMappr([
 MapType<CommonDto, CommonObject>()
], modules: [
  ModuleAMappr()
])
class Mappr extends $Mappr {}
```

In ModuleA we have defined mapping between **UserDto** -> **User** which has dependency on **CommonDto** (CommonObject)

```dart
class UserDto {
  final int id;
  final CommonDto roleKey;
}
```

Ideally we could defined ModuleA mappr like

```dart
@AutoMappr([
 MapType<UserDto , User>()
])
class ModuleAMappr extends $ModuleAMappr {}
```

**How to extend it** ?

1. First - just mark it as "module"

```dart
@AutoMappr([
 MapType<UserDto , User>()
], isModule: true)
class ModuleAMappr extends $ModuleAMappr {}
```
 This could disable some checks, etc., but not sure if it can be done this way. Needs more investegation.

2. Second - define "ancestors" / "dependencies"
```dart
@AutoMappr([
 MapType<UserDto , User>()
], dependsOn: [
   CommonMappr //Type, not instance of CommonMappr
])
class ModuleAMappr extends $ModuleAMappr {}
```
where CommonMappr should be defined as standalone mappr

```dart
@AutoMappr([
 MapType<CommonDto, CommonObject>()
])
class ComnonMappr extends $CommonMappr {}
```

Final global main mappr could be just

```dart
@AutoMappr([
], modules: [
  CommonMappr(),
  ModuleAMappr()
])
class Mappr extends $Mappr {}
```
With this approach, each automappr could proably read `@AutoMappr` annotation from its dependencies and check if there is existing mapping etc.

**Version info**
 - Package version : 1.4.0

**Comment by tenhobi** [comment]
I agree that having the option to use/include other auto-mapper modules can be helpful.

**Comment by tenhobi** [comment]
Implemented, will be part of v2.
