### ISSUE TITLE
Nested mapping (modules) doesn't work

### ISSUE THREAD

**Issue by srheede** [netglade/auto_mappr#81]
**Describe the bug**

**To Reproduce**
Code to reproduce issue: 
I followed this documentation:
https://pub.dev/packages/auto_mappr#map-objects-mapping

These steps:

"Modules 
Each AutoMappr class can be used as a module. That means a mappr used inside of another mappr. Each AutoMappr class can include a list of modules that can be used to nest modules and use all of its underlying mappings.

Applications are often split into independent parts (we will call them features). Each feature should probably have its own independent mappr, that is used as a module.

Imagine that in a feature you have a local mappr UserMappr.

// file: user_mappr.dart
@AutoMappr([
  MapType<UserDto, User>(),
])
class UserMappr extends $UserMappr {
  const UserMappr(); // must implement const constructor
}
And in some global place, you can have a main mappr that unifies all smaller mapprs (UserMappr in this case). As usual, it can also set it's own mappings (MapType<GroupDto, Group>()).

// file: main_mappr.dart
@AutoMappr(
  [
    MapType<GroupDto, Group>(),
  ],
  modules: [
    UserMappr(), // use module
  ],
)
class MainMappr extends $MainMappr {}"

**Expected behavior**

**Version info**
 - Package version : 
  auto_mappr_annotation: ^1.1.0
  auto_mappr: ^1.4.0

**Additional context**
Expected: Mapping of 2 classes while mapping parent class.
Result: Trying to map nested object from "HiveSetImages images -> SetImages images" but no mapping is configured.

**Comment by petrnymsa** [comment]
@srheede  Hi can you post your configured mappers?

**Comment by srheede** [comment]
Hi, thanks for the quick response. I tried a mapping a different object. Getting the same kind of error. Here's the code:


Mappers that aren't accepting nested mappers (modules):

`@AutoMappr(
  [
    MapType<PokemonCard, HivePokemonCard>(),
  ],
  modules: [
    HiveSupertypeMapper(),
  ],
)
class HivePokemonCardMapper extends $HivePokemonCardMapper {
  const HivePokemonCardMapper();
}

@AutoMappr(
  [
    MapType<HivePokemonCard, PokemonCard>(),
  ],
  modules: [
    SupertypeMapper(),
  ],
)
class PokemonCardMapper extends $PokemonCardMapper {
  const PokemonCardMapper();
}`

Configured "nested" mappers that ran without a problem:

`@AutoMappr([
  MapType<Supertype, HiveSupertype>(),
])
class HiveSupertypeMapper extends $HiveSupertypeMapper {
  const HiveSupertypeMapper();
}

@AutoMappr([
  MapType<HiveSupertype, Supertype>(),
])
class SupertypeMapper extends $SupertypeMapper {
  const SupertypeMapper();
}`

**Comment by tenhobi** [comment]
I can't see `HiveSetImages images -> SetImages images` in these mapprs tho.

**Comment by srheede** [comment]
Sorry that is because I tried a different object. The error I am getting now is:
Trying to map nested object from "Supertype supertype -> HiveSupertype supertype" but no mapping is configured.

That is with the HivePokemonCardMapper() in my previous response.

**Comment by tenhobi** [comment]
And just to make sure, you are concerting it on HivePokemonCardMapper? 

Btw. did you face some errors workout Hive? I think it uses some generated files no?

**Comment by petrnymsa** [comment]
@srheede If you try configure mappers without modules  is it working? 

Can you re-run generation with -v flag

```
dart pub run build_runner build --delete-conflicting-outputs -v
```

and paste results here (with formatting). 

Thank you

**Comment by srheede** [comment]
> And just to make sure, you are concerting it on HivePokemonCardMapper?
> 
> Btw. did you face some errors workout Hive? I think it uses some generated files no?

It could be that Hive is causing conflicts. I didn't have any issues with the hive generated files though.

**Comment by srheede** [comment]
> @srheede If you try configure mappers without modules is it working?
> 
> Can you re-run generation with -v flag
> 
> ```
> dart pub run build_runner build --delete-conflicting-outputs -v
> ```
> 
> and paste results here (with formatting).
> 
> Thank you

@petrnymsa 

Running the mappers with modules:
`FINE: Pub 3.0.3
MSG : Deprecated. Use `dart run` instead.
FINE: Package Config up to date.
FINE: Package Config up to date.
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 607ms

[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Reading cached asset graph...
[INFO] BuildDefinition:Reading cached asset graph completed, took 108ms

[INFO] BuildDefinition:Checking for updates since last build...
[INFO] BuildDefinition:Checking for updates since last build completed, took 4.3s

[INFO] Build:Running build...
[INFO] Heartbeat:3.0s elapsed, 0/1 actions completed.
[FINE] hive_generator on lib/mappers/auto_mappers.dart:Running TypeAdapterGenerator
[FINE] auto_mappr on lib/mappers/auto_mappers.dart:Running AutoMapprGenerator
[SEVERE] auto_mappr on lib/mappers/auto_mappers.dart:

Trying to map nested object from "Supertype supertype -> HiveSupertype supertype" but no mapping is configured.
package:auto_mappr/src/builder/value_assignment_builder.dart 232:7        ValueAssignmentBuilder._assignNestedObject
package:auto_mappr/src/builder/value_assignment_builder.dart 55:14        ValueAssignmentBuilder.build
package:auto_mappr/src/builder/map_model_body_method_builder.dart 255:13  MapModelBodyMethodBuilder._mapConstructor
package:auto_mappr/src/builder/map_model_body_method_builder.dart 227:12  MapModelBodyMethodBuilder._processConstructorMapping
package:auto_mappr/src/builder/map_model_body_method_builder.dart 58:35   MapModelBodyMethodBuilder.build
package:auto_mappr/src/builder/auto_mappr_builder.dart 137:15             AutoMapprBuilder._buildMethods.<fn>
package:code_builder/src/specs/method.g.dart 323:33                       _$MethodBuilder.update
package:code_builder/src/specs/method.g.dart 38:29                        new _$Method
package:auto_mappr/src/builder/auto_mappr_builder.dart 122:9              AutoMapprBuilder._buildMethods
package:auto_mappr/src/builder/auto_mappr_builder.dart 44:34              AutoMapprBuilder.build.<fn>.<fn>
package:code_builder/src/specs/class.g.dart 345:33                        _$ClassBuilder.update
package:code_builder/src/specs/class.g.dart 40:28                         new _$Class
package:auto_mappr/src/builder/auto_mappr_builder.dart 40:13              AutoMapprBuilder.build.<fn>
package:code_builder/src/specs/library.g.dart 187:33                      _$LibraryBuilder.update
package:code_builder/src/specs/library.g.dart 24:30                       new _$Library
package:auto_mappr/src/builder/auto_mappr_builder.dart 35:12              AutoMapprBuilder.build
package:auto_mappr/src/generator/auto_mappr_generator.dart 93:28          AutoMapprGenerator.generateForAnnotatedElement
package:source_gen/src/generator_for_annotation.dart 53:30                GeneratorForAnnotation.generate
package:source_gen/src/builder.dart 355:33                                _generate

[INFO] Build:Running build completed, took 3.5s

[INFO] Build:Caching finalized dependency graph...
[INFO] Build:Caching finalized dependency graph completed, took 50ms

[SEVERE] Build:
Failed after 3.6s
IO  : Writing 10597 characters to text file C:\Users\User\AppData\Local\Pub\Cache\log\pub_log.txt.
MSG : Logs written to C:\Users\User\AppData\Local\Pub\Cache\log\pub_log.txt.`


By "configure mappers without modules" you mean to remove them here?
`@AutoMappr(
  [
    MapType<PokemonCard, HivePokemonCard>(),
  ],
  modules: [
    HiveSupertypeMapper(),      // Here?
  ],
)
class HivePokemonCardMapper extends $HivePokemonCardMapper {}`

I get the same result if I do that.

**Comment by tenhobi** [comment]
Hi @srheede, we analyzed your logs and we think that we see what's wrong since it might be confusing in the README.

Correct me if wrong, but we think now you use modules with intention that its mappings will be used for your MapTypes. 

```
@AutoMappr(
  [
    MapType<PokemonCard, HivePokemonCard>(),
  ],
  modules: [
    HiveSupertypeMapper(),
  ],
)
class HivePokemonCardMapper extends $HivePokemonCardMapper {
  const HivePokemonCardMapper();
}
```

Meaning that you use some mappings from `HiveSupertypeMapper` to inner staff from `PokemonCard`, right?

Currently, modules are "designed" to be independent, and disjunct. And are implemented in this way. That means they are modules in "disjunct merging/grouping" meaning. 

We would also like to have "import/use modules", basically copypasting maptypes from modules into current ones (#79). But right now mappers can only reference mapping to other modules, they cannot use them internally.

Might this be the issue in your case?

**Comment by tenhobi** [comment]
Implemented, will be part of v2.
